/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ReportAssessmentIdRouteImport } from './routes/report.$assessmentId'
import { Route as AssessmentStartRouteImport } from './routes/assessment.start'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminRecommendationsRouteImport } from './routes/admin.recommendations'
import { Route as AdminQuestionsRouteImport } from './routes/admin.questions'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminAssessmentsRouteImport } from './routes/admin.assessments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAssessmentsIndexRouteImport } from './routes/admin.assessments.index'
import { Route as AssessmentAssessmentIdQuestionnaireRouteImport } from './routes/assessment.$assessmentId.questionnaire'
import { Route as AdminAssessmentsAssessmentIdRouteImport } from './routes/admin.assessments.$assessmentId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportAssessmentIdRoute = ReportAssessmentIdRouteImport.update({
  id: '/report/$assessmentId',
  path: '/report/$assessmentId',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentStartRoute = AssessmentStartRouteImport.update({
  id: '/assessment/start',
  path: '/assessment/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecommendationsRoute = AdminRecommendationsRouteImport.update({
  id: '/admin/recommendations',
  path: '/admin/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuestionsRoute = AdminQuestionsRouteImport.update({
  id: '/admin/questions',
  path: '/admin/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/admin/categories',
  path: '/admin/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentsRoute = AdminAssessmentsRouteImport.update({
  id: '/admin/assessments',
  path: '/admin/assessments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAssessmentsIndexRoute = AdminAssessmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAssessmentsRoute,
} as any)
const AssessmentAssessmentIdQuestionnaireRoute =
  AssessmentAssessmentIdQuestionnaireRouteImport.update({
    id: '/assessment/$assessmentId/questionnaire',
    path: '/assessment/$assessmentId/questionnaire',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAssessmentsAssessmentIdRoute =
  AdminAssessmentsAssessmentIdRouteImport.update({
    id: '/$assessmentId',
    path: '/$assessmentId',
    getParentRoute: () => AdminAssessmentsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/report/$assessmentId': typeof ReportAssessmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/assessment/$assessmentId/questionnaire': typeof AssessmentAssessmentIdQuestionnaireRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/report/$assessmentId': typeof ReportAssessmentIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/assessment/$assessmentId/questionnaire': typeof AssessmentAssessmentIdQuestionnaireRoute
  '/admin/assessments': typeof AdminAssessmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/assessments': typeof AdminAssessmentsRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/questions': typeof AdminQuestionsRoute
  '/admin/recommendations': typeof AdminRecommendationsRoute
  '/admin/users': typeof AdminUsersRoute
  '/assessment/start': typeof AssessmentStartRoute
  '/report/$assessmentId': typeof ReportAssessmentIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/assessments/$assessmentId': typeof AdminAssessmentsAssessmentIdRoute
  '/assessment/$assessmentId/questionnaire': typeof AssessmentAssessmentIdQuestionnaireRoute
  '/admin/assessments/': typeof AdminAssessmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/recommendations'
    | '/admin/users'
    | '/assessment/start'
    | '/report/$assessmentId'
    | '/admin/'
    | '/admin/assessments/$assessmentId'
    | '/assessment/$assessmentId/questionnaire'
    | '/admin/assessments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/analytics'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/recommendations'
    | '/admin/users'
    | '/assessment/start'
    | '/report/$assessmentId'
    | '/admin'
    | '/admin/assessments/$assessmentId'
    | '/assessment/$assessmentId/questionnaire'
    | '/admin/assessments'
  id:
    | '__root__'
    | '/'
    | '/admin/analytics'
    | '/admin/assessments'
    | '/admin/categories'
    | '/admin/login'
    | '/admin/questions'
    | '/admin/recommendations'
    | '/admin/users'
    | '/assessment/start'
    | '/report/$assessmentId'
    | '/admin/'
    | '/admin/assessments/$assessmentId'
    | '/assessment/$assessmentId/questionnaire'
    | '/admin/assessments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssessmentsRoute: typeof AdminAssessmentsRouteWithChildren
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminQuestionsRoute: typeof AdminQuestionsRoute
  AdminRecommendationsRoute: typeof AdminRecommendationsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AssessmentStartRoute: typeof AssessmentStartRoute
  ReportAssessmentIdRoute: typeof ReportAssessmentIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AssessmentAssessmentIdQuestionnaireRoute: typeof AssessmentAssessmentIdQuestionnaireRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$assessmentId': {
      id: '/report/$assessmentId'
      path: '/report/$assessmentId'
      fullPath: '/report/$assessmentId'
      preLoaderRoute: typeof ReportAssessmentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/start': {
      id: '/assessment/start'
      path: '/assessment/start'
      fullPath: '/assessment/start'
      preLoaderRoute: typeof AssessmentStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recommendations': {
      id: '/admin/recommendations'
      path: '/admin/recommendations'
      fullPath: '/admin/recommendations'
      preLoaderRoute: typeof AdminRecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/questions': {
      id: '/admin/questions'
      path: '/admin/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof AdminQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/admin/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments': {
      id: '/admin/assessments'
      path: '/admin/assessments'
      fullPath: '/admin/assessments'
      preLoaderRoute: typeof AdminAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments/': {
      id: '/admin/assessments/'
      path: '/'
      fullPath: '/admin/assessments/'
      preLoaderRoute: typeof AdminAssessmentsIndexRouteImport
      parentRoute: typeof AdminAssessmentsRoute
    }
    '/assessment/$assessmentId/questionnaire': {
      id: '/assessment/$assessmentId/questionnaire'
      path: '/assessment/$assessmentId/questionnaire'
      fullPath: '/assessment/$assessmentId/questionnaire'
      preLoaderRoute: typeof AssessmentAssessmentIdQuestionnaireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/assessments/$assessmentId': {
      id: '/admin/assessments/$assessmentId'
      path: '/$assessmentId'
      fullPath: '/admin/assessments/$assessmentId'
      preLoaderRoute: typeof AdminAssessmentsAssessmentIdRouteImport
      parentRoute: typeof AdminAssessmentsRoute
    }
  }
}

interface AdminAssessmentsRouteChildren {
  AdminAssessmentsAssessmentIdRoute: typeof AdminAssessmentsAssessmentIdRoute
  AdminAssessmentsIndexRoute: typeof AdminAssessmentsIndexRoute
}

const AdminAssessmentsRouteChildren: AdminAssessmentsRouteChildren = {
  AdminAssessmentsAssessmentIdRoute: AdminAssessmentsAssessmentIdRoute,
  AdminAssessmentsIndexRoute: AdminAssessmentsIndexRoute,
}

const AdminAssessmentsRouteWithChildren =
  AdminAssessmentsRoute._addFileChildren(AdminAssessmentsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssessmentsRoute: AdminAssessmentsRouteWithChildren,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminQuestionsRoute: AdminQuestionsRoute,
  AdminRecommendationsRoute: AdminRecommendationsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AssessmentStartRoute: AssessmentStartRoute,
  ReportAssessmentIdRoute: ReportAssessmentIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AssessmentAssessmentIdQuestionnaireRoute:
    AssessmentAssessmentIdQuestionnaireRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
