/** Central registry of REST paths so the frontend client and worker router never drift apart. */
export const API_ROUTES = {
  assessmentStart: "/api/assessment/start",
  questions: "/api/questions",
  assessmentSubmit: "/api/assessment/submit",
  report: (id: string) => `/api/report/${id}`,
  reportPdf: (id: string) => `/api/report/${id}/pdf`,
  adminLogin: "/api/admin/login",
  adminQuestions: "/api/admin/questions",
  adminQuestion: (id: string) => `/api/admin/questions/${id}`,
  adminAssessments: "/api/admin/assessments",
  adminAssessment: (id: string) => `/api/admin/assessments/${id}`,
  adminCategories: "/api/admin/categories",
  adminCategory: (id: string) => `/api/admin/categories/${id}`,
  adminRecommendations: "/api/admin/recommendations",
  adminRecommendation: (id: string) => `/api/admin/recommendations/${id}`,
  adminAnalytics: "/api/admin/analytics",
  adminUsers: "/api/admin/users",
  adminUser: (id: string) => `/api/admin/users/${id}`,
} as const;
